project_id = "rpxygdaimdiarjpfmswl"

[functions.outlook-auth]
verify_jwt = true

[functions.send-bulk-email]
verify_jwt = true

[functions.send-team-invite]
verify_jwt = true

[functions.ai-semantic-search]
verify_jwt = false

[functions.execute-campaign]
verify_jwt = true

[functions.execute-workflow]
verify_jwt = true

[functions.send-email]
verify_jwt = true

[functions.send-sms]
verify_jwt = true

[functions.generate-automation]
verify_jwt = false

[functions.aircall-api]
verify_jwt = true

[functions.aircall-webhook]
verify_jwt = false
